apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ratty-quail-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-hub/ratty-quail-dotnet-basic-gitops