apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ratty-quail-dotnet-basic
  janus-idp.io/tekton: ratty-quail-dotnet-basic
  backstage.io/kubernetes-id: ratty-quail-dotnet-basic
  backstage.io/kubernetes-namespace: oc-ci-e2e 
  app.kubernetes.io/part-of: ratty-quail-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
